"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  let isAuthenticated = false;
  if (typeof window !== "undefined") {
    const userId = localStorage.getItem("_id");
    const accessToken = localStorage.getItem("accessToken");
    const username = localStorage.getItem("username");
    isAuthenticated = !!userId && !!accessToken && !!username;
  }
  useEffect(() => {
    if (!isAuthenticated) {
      router.push("login");
    } else {
      router.push("/");
    }
  }, []);

  const handleLogout = () => {
    if (typeof window !== "undefined") {
      localStorage.setItem("accessToken", "");
      localStorage.setItem("username", "");
      localStorage.setItem("_id", "");
      router.push("/login");
    }
  };

  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <div className="flex h-screen">
          <div className="w-1/4 bg-gray-800 p-4 text-white">
            <h1 className="text-3xl font-bold mb-6">TO DO LIST</h1>
            <nav>
              <ul>
                <li className="mb-4">
                  <Link href="/">
                    <p className="text-blue-500">Today&apos;s Tasks</p>
                  </Link>
                </li>
                <li className="mb-4">
                  <Link href="/upcoming">
                    <p className="text-blue-500">Upcoming Tasks</p>
                  </Link>
                </li>
                <li className="mb-4">
                  <Link href="/filters-&-labels">
                    <p className="text-blue-500">Filters & Labels</p>
                  </Link>
                </li>
                <li>
                  <button
                    onClick={handleLogout}
                    className="text-blue-500 cursor-pointer"
                  >
                    Logout
                  </button>
                </li>
              </ul>
            </nav>
          </div>
          <div className="flex-1 p-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
